### ISSUE TITLE
Bug z postami

### ISSUE THREAD

**Issue by suchencjusz** [kacpereqo/menel.me#3]
Trzeba robić reloga programu żeby nowy post się wyświetlił xD 

@kacpereqo 

obstawiam cache 
https://github.com/kacpereqo/menel.me/blob/67ee7595b754cf805d15210b97bdff0e6b4f1d1e/main.py#L22-L24

**Comment by suchencjusz** [comment]
wtf https://flask-caching.readthedocs.io/en/latest/#clearing-cache

**Comment by kacpereqo** [comment]
A KURWA CHUJ, DZIALA WSZYSTKO BO WYJEBALEM CACHOWANIE JAKIS TYDZIEN TEMU b))))))))))
